# Generated by Django 5.0.6 on 2024-05-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MailingMessage',
        ),
    ]
